"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import ThemedDropdown from "../components/ThemedDropdown";
import ComingSoon from "../components/ComingSoon";

const TOOL_STATUS = "live";

const genderOptions = [
  { value: "male", label: "Male" },
  { value: "female", label: "Female" },
];

const activityOptions = [
  { value: "sedentary", label: "Sedentary (little or no exercise)" },
  { value: "light", label: "Lightly Active (1-3 days/week)" },
  { value: "moderate", label: "Moderately Active (3-5 days/week)" },
  { value: "active", label: "Very Active (6-7 days/week)" },
  { value: "extra", label: "Extra Active (intense daily exercise)" },
];

const unitOptions = [
  { value: "metric", label: "Metric (kg / cm)" },
  { value: "imperial", label: "Imperial (lbs / ft-in)" },
];

const activityMultipliers = {
  sedentary: 1.2,
  light: 1.375,
  moderate: 1.55,
  active: 1.725,
  extra: 1.9,
};

function parseNumber(value) {
  if (value === "" || value === null || value === undefined) {
    return null;
  }
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : null;
}

function formatCalories(value) {
  return `${Math.round(Number(value) || 0).toLocaleString("en-IN")} kcal`;
}

function StatCard({ label, value, subtitle, accent }) {
  return (
    <div
      className={`rounded-2xl border p-4 shadow-sm transition-all duration-200 ease-out hover:-translate-y-0.5 hover:shadow-md ${
        accent
          ? "border-orange-200 bg-orange-50 hover:border-orange-300 hover:bg-orange-50"
          : "border-slate-200 bg-slate-50 hover:border-slate-300 hover:bg-white"
      }`}
    >
      <p className="text-xs font-medium uppercase tracking-wider text-slate-500">{label}</p>
      <p className={`mt-2 text-2xl font-bold tracking-tight tabular-nums ${accent ? "text-orange-700" : "text-slate-900"}`}>{value}</p>
      {subtitle ? <p className="mt-1 text-sm text-slate-500">{subtitle}</p> : null}
    </div>
  );
}

function InsightCard({ label, value, subtitle }) {
  return (
    <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm transition-all duration-200 ease-out hover:-translate-y-0.5 hover:border-slate-300 hover:shadow-md">
      <p className="text-xs font-medium uppercase tracking-wider text-slate-500">{label}</p>
      <p className="mt-2 text-lg font-semibold text-slate-900">{value}</p>
      {subtitle ? <p className="mt-1 text-sm text-slate-500">{subtitle}</p> : null}
    </div>
  );
}

function SkeletonCard() {
  return (
    <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm animate-pulse">
      <div className="h-3 w-24 rounded-full bg-slate-200" />
      <div className="mt-4 h-9 w-28 rounded-full bg-slate-200" />
      <div className="mt-2 h-3 w-32 rounded-full bg-slate-100" />
    </div>
  );
}

function MacroBar({ label, grams, percent, color }) {
  return (
    <div className="flex flex-col gap-1.5">
      <div className="flex items-center justify-between text-sm">
        <span className="font-medium text-slate-700">{label}</span>
        <span className="tabular-nums text-slate-500">{grams}g ({percent}%)</span>
      </div>
      <div className="h-2 w-full rounded-full bg-slate-100 overflow-hidden">
        <div
          className={`h-full rounded-full transition-all duration-500 ease-out ${color}`}
          style={{ width: `${percent}%` }}
        />
      </div>
    </div>
  );
}

function buildReport({ age, gender, heightCm, weightKg, activityLevel, unit, result }) {
  const activityLabel = activityOptions.find((o) => o.value === activityLevel)?.label ?? activityLevel;
  return [
    "Calorie Calculator Report",
    "",
    "--- Profile ---",
    `Age: ${age} years`,
    `Gender: ${gender === "male" ? "Male" : "Female"}`,
    `Height: ${Math.round(heightCm)} cm`,
    `Weight: ${weightKg.toFixed(1)} kg`,
    `Activity Level: ${activityLabel}`,
    "",
    "--- Results ---",
    `BMR (Basal Metabolic Rate): ${formatCalories(result.bmr)}`,
    `TDEE (Total Daily Energy Expenditure): ${formatCalories(result.tdee)}`,
    "",
    `Maintenance Calories: ${formatCalories(result.maintenance)}`,
    `Weight Loss (moderate deficit): ${formatCalories(result.weightLoss)}`,
    `Extreme Weight Loss (aggressive deficit): ${formatCalories(result.extremeLoss)}`,
    `Weight Gain (lean bulk): ${formatCalories(result.weightGain)}`,
    `Aggressive Weight Gain: ${formatCalories(result.aggressiveGain)}`,
    "",
    "--- Maintenance Macro Split ---",
    `Protein: ${result.macros.protein}g (${result.macros.proteinPct}%)`,
    `Carbohydrates: ${result.macros.carbs}g (${result.macros.carbsPct}%)`,
    `Fat: ${result.macros.fat}g (${result.macros.fatPct}%)`,
    "",
    "Formula: Mifflin-St Jeor equation",
    "Generated by BoringTools Calorie Calculator",
  ].join("\n");
}

export default function CalorieCalculatorPage() {
  if (TOOL_STATUS === "upcoming") {
    return <ComingSoon toolName="Calorie Calculator" />;
  }
  const [age, setAge] = useState("25");
  const [gender, setGender] = useState("male");
  const [unit, setUnit] = useState("metric");
  const [height, setHeight] = useState("175");
  const [heightFt, setHeightFt] = useState("5");
  const [heightIn, setHeightIn] = useState("9");
  const [weight, setWeight] = useState("70");
  const [activityLevel, setActivityLevel] = useState("moderate");
  const [toast, setToast] = useState({ type: "", message: "" });
  const [animateCards, setAnimateCards] = useState(false);
  const toastTimerRef = useRef(null);

  const heightCm = useMemo(() => {
    if (unit === "metric") {
      return parseNumber(height);
    }
    const ft = parseNumber(heightFt);
    const inches = parseNumber(heightIn) || 0;
    if (ft === null) return null;
    return (ft * 12 + inches) * 2.54;
  }, [unit, height, heightFt, heightIn]);

  const weightKg = useMemo(() => {
    const w = parseNumber(weight);
    if (w === null) return null;
    return unit === "metric" ? w : w * 0.453592;
  }, [unit, weight]);

  const validationError = useMemo(() => {
    const parsedAge = parseNumber(age);
    if (parsedAge === null || parsedAge < 1 || parsedAge > 120) {
      return "Enter a valid age between 1 and 120.";
    }
    if (heightCm === null || heightCm < 50 || heightCm > 300) {
      return "Enter a valid height.";
    }
    if (weightKg === null || weightKg < 10 || weightKg > 500) {
      return "Enter a valid weight.";
    }
    return "";
  }, [age, heightCm, weightKg]);

  const result = useMemo(() => {
    const parsedAge = parseNumber(age);

    if (validationError || parsedAge === null || heightCm === null || weightKg === null) {
      return null;
    }

    // Mifflin-St Jeor equation
    let bmr;
    if (gender === "male") {
      bmr = 10 * weightKg + 6.25 * heightCm - 5 * parsedAge + 5;
    } else {
      bmr = 10 * weightKg + 6.25 * heightCm - 5 * parsedAge - 161;
    }

    const multiplier = activityMultipliers[activityLevel] || 1.55;
    const tdee = bmr * multiplier;

    const maintenance = tdee;
    const weightLoss = tdee - 500;
    const extremeLoss = tdee - 1000;
    const weightGain = tdee + 500;
    const aggressiveGain = tdee + 1000;

    // Macro breakdown for maintenance (balanced split)
    const proteinPct = 30;
    const carbsPct = 40;
    const fatPct = 30;
    const protein = Math.round((maintenance * (proteinPct / 100)) / 4);
    const carbs = Math.round((maintenance * (carbsPct / 100)) / 4);
    const fat = Math.round((maintenance * (fatPct / 100)) / 9);

    return {
      bmr,
      tdee,
      maintenance,
      weightLoss: Math.max(weightLoss, 1200),
      extremeLoss: Math.max(extremeLoss, 1000),
      weightGain,
      aggressiveGain,
      macros: { protein, carbs, fat, proteinPct, carbsPct, fatPct },
    };
  }, [age, gender, heightCm, weightKg, activityLevel, validationError]);

  const summaryText = useMemo(() => {
    if (!age && !weight) {
      return "Enter your details to see your daily calorie needs.";
    }
    if (!result) {
      return validationError || "Checking your details...";
    }
    return `You need approximately ${formatCalories(result.maintenance)} per day to maintain your current weight.`;
  }, [age, weight, result, validationError]);

  const reportText = useMemo(() => {
    if (!result || heightCm === null || weightKg === null) {
      return "";
    }
    return buildReport({
      age: parseNumber(age) || 0,
      gender,
      heightCm,
      weightKg,
      activityLevel,
      unit,
      result,
    });
  }, [age, activityLevel, gender, heightCm, result, unit, weightKg]);

  useEffect(() => {
    if (!result) {
      setAnimateCards(false);
      return undefined;
    }
    setAnimateCards(true);
    const timer = window.setTimeout(() => setAnimateCards(false), 180);
    return () => window.clearTimeout(timer);
  }, [result]);

  useEffect(() => {
    return () => {
      if (toastTimerRef.current) {
        window.clearTimeout(toastTimerRef.current);
      }
    };
  }, []);

  const showToast = (type, message) => {
    if (toastTimerRef.current) {
      window.clearTimeout(toastTimerRef.current);
    }
    setToast({ type, message });
    toastTimerRef.current = window.setTimeout(() => {
      setToast({ type: "", message: "" });
    }, 1800);
  };

  const copyResults = async () => {
    if (!reportText) return;
    try {
      await navigator.clipboard.writeText(reportText);
      showToast("success", "Results copied to clipboard.");
    } catch {
      showToast("error", "Copy failed. Try again.");
    }
  };

  const downloadReport = () => {
    if (!reportText || typeof window === "undefined") return;
    const blob = new Blob([reportText], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = "calorie-calculator-report.txt";
    document.body.appendChild(link);
    link.click();
    link.remove();
    URL.revokeObjectURL(url);
    showToast("success", "Report downloaded.");
  };

  const clearInputs = () => {
    setAge("");
    setGender("male");
    setUnit("metric");
    setHeight("");
    setHeightFt("");
    setHeightIn("");
    setWeight("");
    setActivityLevel("moderate");
    setToast({ type: "", message: "" });
    showToast("success", "Inputs cleared.");
  };

  const showEmptyState = !result && !validationError;
  const showSkeleton = Boolean(result && animateCards);

  return (
    <div className="min-h-screen bg-slate-50 flex items-center justify-center p-4 font-sans">
      <div className="bg-white shadow-lg rounded-2xl p-5 sm:p-8 w-full max-w-6xl border border-slate-200 flex flex-col gap-6">
        {/* Hero */}
        <div className="flex flex-col gap-2 items-center text-center">
          <p className="text-xs font-semibold uppercase tracking-[0.3em] text-orange-600">Health</p>
          <h1 className="text-3xl sm:text-4xl font-bold tracking-tight text-slate-900">Calorie Calculator</h1>
          <p className="text-slate-500 text-base max-w-2xl">
            Estimate your daily calorie needs based on age, gender, height, weight, and activity level.
          </p>
        </div>

        {/* Input + Summary Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-[1.05fr_0.95fr] gap-4 items-stretch">
          {/* Input Panel */}
          <div className="rounded-2xl border border-slate-200 bg-white p-4 sm:p-6 shadow-sm transition-all duration-200 hover:-translate-y-0.5 hover:border-slate-300 hover:shadow-md">
            <div className="flex items-start justify-between gap-3">
              <div>
                <p className="text-xs font-semibold uppercase tracking-[0.24em] text-orange-600">Inputs</p>
                <h2 className="mt-1 text-lg font-semibold tracking-tight text-slate-900">Enter your details</h2>
              </div>
            </div>

            <div className="mt-6 grid grid-cols-1 gap-4">
              {/* Age + Gender */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                <label className="flex flex-col gap-2">
                  <span className="text-sm font-medium text-slate-900">Age</span>
                  <input
                    type="number"
                    min="1"
                    max="120"
                    step="1"
                    value={age}
                    onChange={(e) => setAge(e.target.value)}
                    placeholder="e.g. 25"
                    className="w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-slate-900 placeholder:text-slate-400 shadow-sm transition focus:outline-none focus:ring-2 focus:ring-slate-900"
                  />
                </label>
                <label className="flex flex-col gap-2">
                  <span className="text-sm font-medium text-slate-900">Gender</span>
                  <ThemedDropdown
                    ariaLabel="Select gender"
                    value={gender}
                    options={genderOptions}
                    onChange={(value) => setGender(value)}
                  />
                </label>
              </div>

              {/* Unit System */}
              <label className="flex flex-col gap-2">
                <span className="text-sm font-medium text-slate-900">Unit System</span>
                <ThemedDropdown
                  ariaLabel="Select unit system"
                  value={unit}
                  options={unitOptions}
                  onChange={(value) => setUnit(value)}
                />
              </label>

              {/* Height + Weight */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                {unit === "metric" ? (
                  <label className="flex flex-col gap-2">
                    <span className="text-sm font-medium text-slate-900">Height (cm)</span>
                    <input
                      type="number"
                      min="50"
                      max="300"
                      step="0.1"
                      value={height}
                      onChange={(e) => setHeight(e.target.value)}
                      placeholder="e.g. 175"
                      className="w-full rounded-xl border border-slate-300 bg-slate-50 px-4 py-3 text-slate-900 placeholder:text-slate-400 shadow-sm transition focus:outline-none focus:ring-2 focus:ring-slate-900"
                    />
                  </label>
                ) : (
                  <div className="flex flex-col gap-2">
                    <span className="text-sm font-medium text-slate-900">Height (ft / in)</span>
                    <div className="flex gap-2">
                      <input
                        type="number"
                        min="1"
                        max="8"
                        step="1"
                        value={heightFt}
                        onChange={(e) => setHeightFt(e.target.value)}
                        placeholder="ft"
                        className="w-full rounded-xl border border-slate-300 bg-slate-50 px-4 py-3 text-slate-900 placeholder:text-slate-400 shadow-sm transition focus:outline-none focus:ring-2 focus:ring-slate-900"
                      />
                      <input
                        type="number"
                        min="0"
                        max="11"
                        step="1"
                        value={heightIn}
                        onChange={(e) => setHeightIn(e.target.value)}
                        placeholder="in"
                        className="w-full rounded-xl border border-slate-300 bg-slate-50 px-4 py-3 text-slate-900 placeholder:text-slate-400 shadow-sm transition focus:outline-none focus:ring-2 focus:ring-slate-900"
                      />
                    </div>
                  </div>
                )}

                <label className="flex flex-col gap-2">
                  <span className="text-sm font-medium text-slate-900">
                    Weight ({unit === "metric" ? "kg" : "lbs"})
                  </span>
                  <input
                    type="number"
                    min="10"
                    max="1000"
                    step="0.1"
                    value={weight}
                    onChange={(e) => setWeight(e.target.value)}
                    placeholder={unit === "metric" ? "e.g. 70" : "e.g. 154"}
                    className="w-full rounded-xl border border-slate-300 bg-slate-50 px-4 py-3 text-slate-900 placeholder:text-slate-400 shadow-sm transition focus:outline-none focus:ring-2 focus:ring-slate-900"
                  />
                </label>
              </div>

              {/* Activity Level */}
              <label className="flex flex-col gap-2">
                <span className="text-sm font-medium text-slate-900">Activity Level</span>
                <ThemedDropdown
                  ariaLabel="Select activity level"
                  value={activityLevel}
                  options={activityOptions}
                  onChange={(value) => setActivityLevel(value)}
                />
              </label>

              {/* Help text + Reset */}
              <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
                <p className="text-sm text-slate-500">Uses the Mifflin-St Jeor equation for accurate BMR estimation.</p>
                <button
                  type="button"
                  onClick={clearInputs}
                  className="inline-flex items-center justify-center rounded-xl border border-orange-200 bg-gradient-to-r from-white to-orange-50 px-4 py-2.5 text-sm font-semibold text-orange-700 shadow-sm shadow-orange-100/60 transition-all duration-200 hover:-translate-y-0.5 hover:border-orange-300 hover:from-orange-50 hover:to-orange-100 hover:text-orange-800 hover:shadow-md hover:shadow-orange-200/60 focus:outline-none focus:ring-2 focus:ring-orange-500"
                >
                  Clear inputs
                </button>
              </div>

              {/* Validation error */}
              {validationError ? (
                <div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-red-700">
                  <p className="text-sm font-semibold">Please fix the highlighted issue.</p>
                  <p className="text-sm">{validationError}</p>
                </div>
              ) : null}
            </div>
          </div>

          {/* Summary Panel */}
          <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4 sm:p-6 shadow-sm transition-all duration-200 hover:border-slate-300 hover:shadow-md">
            <p className="text-xs font-medium uppercase tracking-wider text-slate-500">Summary</p>
            <div className="mt-2 flex flex-col gap-2">
              <h2 className="text-2xl font-bold tracking-tight text-slate-900">{summaryText}</h2>
              <p className="text-sm text-slate-500">Live calculation updates instantly as you type.</p>
            </div>

            {result ? (
              <div className="mt-4 grid grid-cols-1 sm:grid-cols-2 gap-3">
                <div className="rounded-2xl border border-slate-200 bg-white p-4">
                  <p className="text-xs text-slate-500">Basal Metabolic Rate</p>
                  <p className="mt-1 text-lg font-semibold text-slate-900">{formatCalories(result.bmr)}</p>
                </div>
                <div className="rounded-2xl border border-slate-200 bg-white p-4">
                  <p className="text-xs text-slate-500">Total Daily Energy Expenditure</p>
                  <p className="mt-1 text-lg font-semibold text-slate-900">{formatCalories(result.tdee)}</p>
                </div>
              </div>
            ) : null}

            {showEmptyState ? (
              <div className="mt-4 rounded-2xl border border-dashed border-slate-200 bg-white p-6 text-center">
                <p className="text-xs font-medium uppercase tracking-wider text-slate-500">Empty state</p>
                <p className="mt-2 text-lg font-semibold text-slate-900">Enter your details to see results.</p>
                <p className="mt-1 text-sm text-slate-500">BMR, TDEE, calorie targets, and macros will appear here instantly.</p>
              </div>
            ) : null}
          </div>
        </div>

        {/* Calorie Target Cards */}
        <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-3">
          {showSkeleton ? (
            <>
              <SkeletonCard />
              <SkeletonCard />
              <SkeletonCard />
              <SkeletonCard />
              <SkeletonCard />
              <SkeletonCard />
            </>
          ) : result ? (
            <>
              <StatCard label="Maintenance" value={formatCalories(result.maintenance)} subtitle="Calories to maintain current weight" accent />
              <StatCard label="Moderate Weight Loss" value={formatCalories(result.weightLoss)} subtitle="500 kcal daily deficit" />
              <StatCard label="Extreme Weight Loss" value={formatCalories(result.extremeLoss)} subtitle="1,000 kcal daily deficit" />
              <StatCard label="Lean Bulk" value={formatCalories(result.weightGain)} subtitle="500 kcal daily surplus" />
              <StatCard label="Aggressive Gain" value={formatCalories(result.aggressiveGain)} subtitle="1,000 kcal daily surplus" />
              <StatCard label="BMR" value={formatCalories(result.bmr)} subtitle="Calories at complete rest" />
            </>
          ) : null}
        </div>

        {/* Macro Breakdown */}
        {result ? (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            <div className="rounded-2xl border border-slate-200 bg-white p-4 sm:p-6 shadow-sm">
              <p className="text-xs font-semibold uppercase tracking-[0.24em] text-orange-600 mb-1">Macro Breakdown</p>
              <h3 className="text-lg font-semibold tracking-tight text-slate-900 mb-4">Maintenance calorie split</h3>
              <div className="flex flex-col gap-4">
                <MacroBar label="Protein" grams={result.macros.protein} percent={result.macros.proteinPct} color="bg-orange-500" />
                <MacroBar label="Carbohydrates" grams={result.macros.carbs} percent={result.macros.carbsPct} color="bg-amber-400" />
                <MacroBar label="Fat" grams={result.macros.fat} percent={result.macros.fatPct} color="bg-slate-400" />
              </div>
            </div>

            <div className="grid grid-cols-1 gap-3">
              <InsightCard label="Daily Protein Target" value={`${result.macros.protein}g`} subtitle="30% of maintenance calories" />
              <InsightCard label="Daily Carbs Target" value={`${result.macros.carbs}g`} subtitle="40% of maintenance calories" />
              <InsightCard label="Daily Fat Target" value={`${result.macros.fat}g`} subtitle="30% of maintenance calories" />
            </div>
          </div>
        ) : null}

        {/* Action Buttons */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
          <button
            type="button"
            onClick={copyResults}
            className={`rounded-xl border border-slate-900 bg-slate-900 px-4 py-3 font-semibold text-white shadow-sm transition-all duration-200 hover:-translate-y-0.5 hover:bg-black hover:shadow-md focus:outline-none focus:ring-2 focus:ring-slate-900 ${!result || validationError ? "opacity-50 cursor-not-allowed" : ""}`}
            disabled={!result || Boolean(validationError)}
          >
            Copy results
          </button>
          <button
            type="button"
            onClick={downloadReport}
            className={`rounded-xl border border-orange-500 px-4 py-3 font-semibold text-orange-600 shadow-sm transition-all duration-200 hover:-translate-y-0.5 hover:bg-orange-500 hover:text-white hover:shadow-md focus:outline-none focus:ring-2 focus:ring-orange-500 ${!result || validationError ? "opacity-50 cursor-not-allowed" : ""}`}
            disabled={!result || Boolean(validationError)}
          >
            Download report
          </button>
        </div>

        {/* Accuracy Note */}
        <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4">
          <p className="text-xs font-medium uppercase tracking-wider text-slate-500">Accuracy note</p>
          <p className="mt-2 text-sm text-slate-600">
            Calorie estimates use the Mifflin-St Jeor equation, widely regarded as the most reliable formula for predicting basal metabolic rate. Results are general guidelines and individual needs may vary based on body composition, metabolism, and health conditions.
          </p>
        </div>
      </div>

      {/* Toast */}
      {toast.message ? (
        <div
          className={`fixed bottom-6 left-1/2 z-50 -translate-x-1/2 rounded-lg px-4 py-2 text-sm shadow-lg animate-fade-in-out ${toast.type === "error" ? "bg-red-600 text-white" : "bg-slate-900 text-white"}`}
          role="status"
          aria-live="polite"
        >
          {toast.message}
        </div>
      ) : null}

      <style jsx global>{`
        html { font-family: 'Inter', 'Helvetica Neue', Arial, 'system-ui', sans-serif; }
        .animate-fade-in-out {
          animation: fadeInOut 1.8s;
        }
        @keyframes fadeInOut {
          0% { opacity: 0; transform: translateY(10px); }
          10% { opacity: 1; transform: translateY(0); }
          90% { opacity: 1; transform: translateY(0); }
          100% { opacity: 0; transform: translateY(-10px); }
        }
      `}</style>
    </div>
  );
}
